### ExchangeRates API

In [1]:
import pandas as pd

api_url = "https://api.exchangerate-api.com/v4/latest/USD"

df_json = pd.read_json(api_url)
df_json.to_csv("Exports/ExchangeRates.csv")

In [2]:
df_json

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
USD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,USD,2026-08-02,1785628801,1.00
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,USD,2026-08-02,1785628801,3.67
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,USD,2026-08-02,1785628801,65.85
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,USD,2026-08-02,1785628801,82.03
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,USD,2026-08-02,1785628801,366.42
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,USD,2026-08-02,1785628801,238.41
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,USD,2026-08-02,1785628801,16.55
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,USD,2026-08-02,1785628801,18.85
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,USD,2026-08-02,1785628801,26.68
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,USD,2026-08-02,1785628801,26.68

### CatNinja API

In [3]:
import requests

api_url = "https://catfact.ninja/fact"
response = requests.get(api_url)
data = response.json()
data

df = pd.DataFrame([data])
df.to_csv("Exports/CatNinja.csv",index=False)

In [4]:
df

                                                fact  length
0  During the time of the Spanish Inquisition, Po...     259

In [8]:
import requests
import pandas as pd
import time

api_url = "https://catfact.ninja/fact"

facts = []

for i in range(10):
    response = requests.get(api_url)
    data = response.json()
    facts.append(data)
    print(f"Fetched fact {i+1}: {data}")
    time.sleep(1)

df = pd.DataFrame(facts)

df

Fetched: {'fact': "A cat's field of vision is about 200 degrees.", 'length': 45}
Fetched: {'fact': 'Cats that live together sometimes rub each others heads to show that they have no intention of fighting. Young cats do this more often, especially when they are excited.', 'length': 169}
Fetched: {'fact': 'Cats have been domesticated for half as long as dogs have been.', 'length': 63}
Fetched: {'fact': 'The group of words associated with cat (catt,\xa0cath,\xa0chat,\xa0katze) stem from the Latin\xa0catus, meaning domestic cat, as opposed to\xa0feles, or wild cat.', 'length': 147}
Fetched: {'fact': 'The richest cat is Blackie who was left £15 million by his owner, Ben Rea.', 'length': 74}
Fetched: {'fact': 'A cat has the ability to rotate their ears 180 degrees,with the help of 32 muscles that they use to control them.', 'length': 113}
Fetched: {'fact': 'In just seven years, a single pair of cats and their offspring could produce a staggering total of 420,000 kittens.', 'length': 115}
Fetched: {'fact': 'A cat can spend five or more hours a day grooming himself.', 'length': 58}
Fetched: {'fact': 'Cats control the outer ear using 32 muscles; humans use 6', 'length': 57}
Fetched: {'fact': 'The largest cat breed is the Ragdoll. Male Ragdolls weigh between 12 and 20 lbs (5.4-9.0 k). Females weigh between 10 and 15 lbs (4.5-6.8 k).', 'length': 141}

                                                fact  length
0      A cat's field of vision is about 200 degrees.      45
1  Cats that live together sometimes rub each oth...     169
2  Cats have been domesticated for half as long a...      63
3  The group of words associated with cat (catt, ...     147
4  The richest cat is Blackie who was left £15 mi...      74
5  A cat has the ability to rotate their ears 180...     113
6  In just seven years, a single pair of cats and...     115
7  A cat can spend five or more hours a day groom...      58
8  Cats control the outer ear using 32 muscles; h...      57
9  The largest cat breed is the Ragdoll. Male Rag...     141

Then do your analysis

In [10]:
df.sort_values(by="length")

                                                fact  length
0      A cat's field of vision is about 200 degrees.      45
8  Cats control the outer ear using 32 muscles; h...      57
7  A cat can spend five or more hours a day groom...      58
2  Cats have been domesticated for half as long a...      63
4  The richest cat is Blackie who was left £15 mi...      74
5  A cat has the ability to rotate their ears 180...     113
6  In just seven years, a single pair of cats and...     115
9  The largest cat breed is the Ragdoll. Male Rag...     141
3  The group of words associated with cat (catt, ...     147
1  Cats that live together sometimes rub each oth...     169