In [39]:
from bs4 import BeautifulSoup
import pandas as pd

Importing file

In [40]:
file_path = "../../Week 03/005 - Portfolio/index.html"

with open(file_path,'r',encoding='utf-8') as file:
    html = file.read()

Create the soup

In [41]:
soup = BeautifulSoup(html,'html.parser')
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <!-- Meta tags for encoding and responsiveness -->
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <!-- Page title and stylesheet -->
  <title>
   Susara Ouchithya Portfolio
  </title>
  <link href="styles.css" rel="stylesheet"/>
 </head>
 <body>
  <!-- ===== NAVIGATION BAR ===== -->
  <nav class="navbar">
   <div class="nav-container">
    <!-- Portfolio logo / name -->
    <div class="nav-logo" style="font-family:monospace">
     Susara Ouchithya
    </div>
    <!-- Navigation links -->
    <ul class="nav-links">
     <li>
      <a href="#about">
       About
      </a>
     </li>
     <li>
      <a href="#education">
       Education
      </a>
     </li>
     <li>
      <a href="#projects">
       Projects
      </a>
     </li>
     <li>
      <a href="#skills">
       Skills
      </a>
     </li>
     <li>
      <a href="#contact">
       Contact
      </a>
     </li>
    </ul>
   </div>
  </nav>
  <!-- ===== MAIN CONTAINER ===== -->
  <div class="container">
   <!-- ===== HEADER SECTION ===== -->
   <div class="header">
    <!-- Left side: Name, title, contact info -->
    <div class="left-head">
     <h1>
      Susara Ouchithya
     </h1>
     <p class="subtitle">
      Actuarial Associate | Aspiring Researcher | Statistics Graduate
     </p>
     <!-- Profile section: image and contact info -->
     <div class="profile-top">
      <!-- Profile photo -->
      <div class="photo">
       <img alt="Susara Ouchithya" src="images/Ouchithya, Susara.jpg"/>
      </div>
      <!-- Contact information -->
      <div class="contact">
       <p>
        Email:
        <a href="mailto:susara.ouchithya@gmail.com">
         susara.ouchithya@gmail.com
        </a>
       </p>
       <p>
        LinkedIn:
        <a href="https://linkedin.com/in/susaraouchithya" target="_blank">
         linkedin.com/in/susaraouchithya
        </a>
       </p>
       <p>
        GitHub:
        <a href="https://github.com/susara-ouchi" target="_blank">
         github.com/susara-ouchi
        </a>
       </p>
       <p>
        Location: Kottawa, Sri Lanka
       </p>
      </div>
     </div>
    </div>
    <!-- Right side: Slideshow -->
    <div class="right-head">
     <div class="css-slideshow">
      <img alt="Slide 1" src="images/APICTA.jpg"/>
      <img alt="Slide 2" src="images/Guitar.jpg"/>
      <img alt="Slide 3" src="images/Graduation.jpg"/>
      <img alt="Slide 4" src="images/Singing.jpg"/>
      <img alt="Slide 5" src="images/NBQSA.jpg"/>
      <img alt="Slide 6" src="images/Graduation 2.jpg"/>
     </div>
    </div>
   </div>
   <!-- ===== ABOUT SECTION ===== -->
   <div class="section" id="about">
    <h2>
     About Me
    </h2>
    <p>
     My goal is to leverage my skills in machine learning, biostatistics, and risk analysis to develop data-driven solutions with a focus on AI governance, while contributing to research on ethical and societal challenges.
    </p>
   </div>
   <!-- ===== EDUCATION SECTION ===== -->
   <div class="section" id="education">
    <h2>
     Education
    </h2>
    <ul>
     <li>
      <strong>
       BSc (First Class Hons) in Statistics
      </strong>
      – University of Colombo | GPA: 3.92 / 4.00
     </li>
     <li>
      <strong>
       G.C.E. Advanced Level
      </strong>
      – Royal College, Colombo 07 | A, B, B
     </li>
     <li>
      <strong>
       G.C.E. Ordinary Level
      </strong>
      – Royal College, Colombo 07 | 9 A Passes
     </li>
    </ul>
   </div>
   <!-- ===== PROJECTS SECTION ===== -->
   <div class="section" id="projects">
    <h2>
     Projects
    </h2>
    <ul>
     <li>
      <strong>
       MultiDST
      </strong>
      : WHM for Multiple Hypothesis Testing – Gold award at NBQSA 2024, APICTA 2024 Nominee
     </li>
     <li>
      <strong>
       Taste of Asia
      </strong>
      : Delivery Time Prediction with ML
     </li>
     <li>
      <strong>
       Credit 365
      </strong>
      : Credit Score Classification using Random Forest
     </li>
     <li>
      <strong>
       GradGate
      </strong>
      : Graduate Admission Predictor (R Shiny App)
     </li>
    </ul>
   </div>
   <!-- ===== SKILLS SECTION ===== -->
   <div class="section" id="skills">
    <h2>
     Skills &amp; Tools
    </h2>
    <div class="info-grid">
     <div class="info-box">
      <strong>
       Programming:
      </strong>
      <br/>
      Python, R, SQL, HTML/CSS, Git
     </div>
     <div class="info-box">
      <strong>
       Tools:
      </strong>
      <br/>
      Power BI, SPSS, Octave, EViews, Minitab
     </div>
     <div class="info-box">
      <strong>
       Other:
      </strong>
      <br/>
      Public Speaking, Analysis, Model Validation
     </div>
    </div>
   </div>
   <!-- ===== CERTIFICATES SECTION ===== -->
   <div class="section" id="certificates">
    <h2>
     Certificates &amp; Awards
    </h2>
    <ul>
     <li>
      Gold Award – National ICT Awards 2024
     </li>
     <li>
      Best Undergraduate Project – IASSL Awards 2024
     </li>
     <li>
      Dean’s List – University of Colombo (4 years)
     </li>
     <li>
      Justin Samarasekara Award – Most Outstanding Science Student
     </li>
     <li>
      Speech Competition Finalist – Gavel &amp; Toastmasters
     </li>
     <li>
      <a href="http://tinyurl.com/Susara-certificates" target="_blank">
       See all certificates
      </a>
     </li>
    </ul>
   </div>
   <!-- ===== CONTACT FORM ===== -->
   <div class="section" id="contact">
    <h2>
     Contact Me
    </h2>
    <form action="#" method="post">
     <label for="name">
      Name:
     </label>
     <br/>
     <input id="name" name="name" required="" type="text"/>
     <br/>
     <br/>
     <label for="email">
      Email:
     </label>
     <br/>
     <input id="email" name="email" required="" type="email"/>
     <br/>
     <br/>
     <label for="message">
      Message:
     </label>
     <br/>
     <textarea id="message" name="message" required="" rows="5"></textarea>
     <br/>
     <br/>
     <button type="submit">
      Send Message
     </button>
    </form>
   </div>
   <!-- ===== FOOTER ===== -->
   <div class="footer">
    <p>
     Designed by Susara Ouchithya | © 2025
    </p>
   </div>
  </div>
  <!-- End .container -->
 </body>
</html>

# Extract nav items

In [42]:
nav_items = soup.select("nav .nav-links li a")
nav_items

[<a href="#about">About</a>,
 <a href="#education">Education</a>,
 <a href="#projects">Projects</a>,
 <a href="#skills">Skills</a>,
 <a href="#contact">Contact</a>]

In [43]:
for i in nav_items:
    dict_items = {"Section":i.text.strip(), "Link":i.get("href")}
    print(dict_items)

{'Section': 'About', 'Link': '#about'}
{'Section': 'Education', 'Link': '#education'}
{'Section': 'Projects', 'Link': '#projects'}
{'Section': 'Skills', 'Link': '#skills'}
{'Section': 'Contact', 'Link': '#contact'}

In [44]:
nav_items = soup.select("nav .nav-links li a")
nav_data = [{"Section":link.text.strip(), "Link":link.get("href")} for link in nav_items]
nav_data

[{'Section': 'About', 'Link': '#about'},
 {'Section': 'Education', 'Link': '#education'},
 {'Section': 'Projects', 'Link': '#projects'},
 {'Section': 'Skills', 'Link': '#skills'},
 {'Section': 'Contact', 'Link': '#contact'}]

In [45]:
nav_df = pd.DataFrame(nav_data)
nav_df

     Section        Link
0      About      #about
1  Education  #education
2   Projects   #projects
3     Skills     #skills
4    Contact    #contact

### The fun begins here!

Profile

In [46]:
name = soup.select_one(".left-head h1").get_text(strip=True)

subtitle = soup.select_one(".subtitle").get_text(strip=True)

print(name)
print(subtitle)

Susara Ouchithya
Actuarial Associate | Aspiring Researcher | Statistics Graduate

Contact

In [47]:
contact = soup.select_one(".contact")

contact_text = contact.get_text("\n", strip=True)

print(contact_text)

Email:
susara.ouchithya@gmail.com
LinkedIn:
linkedin.com/in/susaraouchithya
GitHub:
github.com/susara-ouchi
Location: Kottawa, Sri Lanka

In [48]:
contact_items = []

for p in contact.find_all("p"):
    contact_items.append(p.get_text(" ", strip=True))

contact_items

['Email: susara.ouchithya@gmail.com',
 'LinkedIn: linkedin.com/in/susaraouchithya',
 'GitHub: github.com/susara-ouchi',
 'Location: Kottawa, Sri Lanka']

About

In [49]:
about_section = soup.find("div", id="about")

about_text = about_section.find("p").get_text(" ", strip=True)

print(about_text)

My goal is to leverage my skills in machine learning, biostatistics, and risk analysis to develop data-driven solutions with a focus on AI governance, while contributing to research on ethical and societal challenges.

Education

In [50]:
education_section = soup.find("div", id="education")

education = []

for item in education_section.find_all("li"):
    education.append(item.get_text(" ", strip=True))

education

['BSc (First Class Hons) in Statistics – University of Colombo | GPA: 3.92 / 4.00',
 'G.C.E. Advanced Level – Royal College, Colombo 07 | A, B, B',
 'G.C.E. Ordinary Level – Royal College, Colombo 07 | 9 A Passes']

Projects

In [51]:
projects_section = soup.find("div", id="projects")

projects = []

for item in projects_section.find_all("li"):
    projects.append(item.get_text(" ", strip=True))

projects

['MultiDST : WHM for Multiple Hypothesis Testing – Gold award at NBQSA 2024, APICTA 2024 Nominee',
 'Taste of Asia : Delivery Time Prediction with ML',
 'Credit 365 : Credit Score Classification using Random Forest',
 'GradGate : Graduate Admission Predictor (R Shiny App)']

Skills

In [52]:
skills_section = soup.find("div", id="skills")

skills = []

for item in skills_section.find_all("div", class_="info-box"):
    skills.append(item.get_text(" ", strip=True))

skills

['Programming: Python, R, SQL, HTML/CSS, Git',
 'Tools: Power BI, SPSS, Octave, EViews, Minitab',
 'Other: Public Speaking, Analysis, Model Validation']

Set up a df

In [53]:
cv_data = []

# Profile
cv_data.append({
    "section": "Profile",
    "subsection": "Name",
    "content": name
})

cv_data.append({
    "section": "Profile",
    "subsection": "Title",
    "content": subtitle
})

# About
cv_data.append({
    "section": "Profile",
    "subsection": "About",
    "content": about_text
})

# Contact
for item in contact_items:
    cv_data.append({
        "section": "Contact",
        "subsection": "",
        "content": item
    })

# Education
for item in education:
    cv_data.append({
        "section": "Education",
        "subsection": "",
        "content": item
    })

# Projects
for item in projects:
    cv_data.append({
        "section": "Projects",
        "subsection": "",
        "content": item
    })

# Skills
for item in skills:
    cv_data.append({
        "section": "Skills",
        "subsection": "",
        "content": item
    })

In [54]:
cv_df = pd.DataFrame(cv_data)

cv_df

      section subsection                                            content
0     Profile       Name                                   Susara Ouchithya
1     Profile      Title  Actuarial Associate | Aspiring Researcher | St...
2     Profile      About  My goal is to leverage my skills in machine le...
3     Contact                             Email: susara.ouchithya@gmail.com
4     Contact                     LinkedIn: linkedin.com/in/susaraouchithya
5     Contact                               GitHub: github.com/susara-ouchi
6     Contact                                  Location: Kottawa, Sri Lanka
7   Education             BSc (First Class Hons) in Statistics – Univers...
8   Education             G.C.E. Advanced Level – Royal College, Colombo...
9   Education             G.C.E. Ordinary Level – Royal College, Colombo...
10   Projects             MultiDST : WHM for Multiple Hypothesis Testing...
11   Projects              Taste of Asia : Delivery Time Prediction with ML
12   Projects             Credit 365 : Credit Score Classification using...
13   Projects             GradGate : Graduate Admission Predictor (R Shi...
14     Skills                    Programming: Python, R, SQL, HTML/CSS, Git
15     Skills                Tools: Power BI, SPSS, Octave, EViews, Minitab
16     Skills             Other: Public Speaking, Analysis, Model Valida...