In [2]:
from bs4 import BeautifulSoup
import pandas as pd

Importing file

In [3]:
file_path = "Sample_portfolio/index.html"

with open(file_path,'r',encoding='utf-8') as file:
    html = file.read()

Create the soup

In [4]:
soup = BeautifulSoup(html,'html.parser')
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <!-- Meta tags for encoding and responsiveness -->
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <!-- Page title and stylesheet -->
  <title>
   Alex Morgan Portfolio
  </title>
  <link href="styles.css" rel="stylesheet"/>
 </head>
 <body>
  <!-- ===== NAVIGATION BAR ===== -->
  <nav class="navbar">
   <div class="nav-container">
    <!-- Portfolio logo / name -->
    <div class="nav-logo" style="font-family:monospace">
     Alex Morgan
    </div>
    <!-- Navigation links -->
    <ul class="nav-links">
     <li>
      <a href="#about">
       About
      </a>
     </li>
     <li>
      <a href="#education">
       Education
      </a>
     </li>
     <li>
      <a href="#projects">
       Projects
      </a>
     </li>
     <li>
      <a href="#skills">
       Skills
      </a>
     </li>
     <li>
      <a href="#contact">
       Contact
      </a>
     </li>
    </ul>
   </div>
  </nav>
  <!-- ===== MAIN CONTAINER ===== -->
  <div class="container">
   <!-- ===== HEADER SECTION ===== -->
   <div class="header">
    <!-- Left side: Name, title, contact info -->
    <div class="left-head">
     <h1>
      Alex Morgan
     </h1>
     <p class="subtitle">
      Data Scientist | Machine Learning Enthusiast | Statistics Graduate
     </p>
     <!-- Profile section: image and contact info -->
     <div class="profile-top">
      <!-- Profile photo -->
      <div class="photo">
       <img alt="Alex Morgan" src="images/P1.jpg"/>
      </div>
      <!-- Contact information -->
      <div class="contact">
       <p>
        Email:
        <a href="mailto:alex.morgan@example.com">
         alex.morgan@example.com
        </a>
       </p>
       <p>
        LinkedIn:
        <a href="https://linkedin.com/in/alex-morgan" target="_blank">
         linkedin.com/in/alex-morgan
        </a>
       </p>
       <p>
        GitHub:
        <a href="https://github.com/alex-morgan" target="_blank">
         github.com/alex-morgan
        </a>
       </p>
       <p>
        Location: Barcelona, Spain
       </p>
      </div>
     </div>
    </div>
    <!-- Right side: Slideshow -->
    <div class="right-head">
     <div class="css-slideshow">
      <img alt="Slide 1" src="images/CS1.jpg"/>
      <img alt="Slide 2" src="images/CS2.jpg"/>
      <img alt="Slide 2" src="images/CS3.jpg"/>
     </div>
    </div>
   </div>
   <!-- ===== ABOUT SECTION ===== -->
   <div class="section" id="about">
    <h2>
     About Me
    </h2>
    <p>
     My goal is to build cool data science projects and share them with the world!
    </p>
   </div>
   <!-- ===== EDUCATION SECTION ===== -->
   <div class="section" id="education">
    <h2>
     Education
    </h2>
    <ul>
     <li>
      <strong>
       BSc (First Class Hons) in Data Science
      </strong>
      – Monash University | GPA: 3.90 / 4.00
     </li>
     <li>
      <strong>
       High School
      </strong>
      – Knox School | Distinction
     </li>
     <li>
      <strong>
       Middle School
      </strong>
      – Glen Waverly High School| Distinction
     </li>
    </ul>
   </div>
   <!-- ===== PROJECTS SECTION ===== -->
   <div class="section" id="projects">
    <h2>
     Projects
    </h2>
    <ul>
     <li>
      <strong>
       DataPulse
      </strong>
      : Customer Churn Prediction with Machine Learning – Winner at DataTech 2024
     </li>
     <li>
      <strong>
       UrbanFlow
      </strong>
      : Travel Time Prediction with ML
     </li>
     <li>
      <strong>
       CreditWise
      </strong>
      : Credit Risk Classification Model
     </li>
     <li>
      <strong>
       StudyPath
      </strong>
      : Student Admission Predictor (R Shiny App)
     </li>
    </ul>
   </div>
   <!-- ===== SKILLS SECTION ===== -->
   <div class="section" id="skills">
    <h2>
     Skills &amp; Tools
    </h2>
    <div class="info-grid">
     <div class="info-box">
      <strong>
       Programming:
      </strong>
      <br/>
      Python, R, SQL, HTML/CSS, Git
     </div>
     <div class="info-box">
      <strong>
       Tools:
      </strong>
      <br/>
      Power BI, Tableau, Jupyter, TensorFlow, PostgreSQL
     </div>
     <div class="info-box">
      <strong>
       Other:
      </strong>
      <br/>
      Data Visualisation, Statistical Analysis, Model Validation
     </div>
    </div>
   </div>
   <!-- ===== CERTIFICATES SECTION ===== -->
   <div class="section" id="certificates">
    <h2>
     Certificates &amp; Awards
    </h2>
    <ul>
     <li>
      Best Undergraduate Project – School of Computing Awards 2024
     </li>
     <li>
      Dean’s List – Monash University (4 years)
     </li>
     <li>
      Data Analytics Excellence Award – Faculty of IT
     </li>
     <li>
      Presentation Competition Finalist – Data Science Society
     </li>
     <li>
      <a href="http://example.com/alex-certificates" target="_blank">
       See all certificates
      </a>
     </li>
    </ul>
   </div>
   <!-- ===== CONTACT FORM ===== -->
   <div class="section" id="contact">
    <h2>
     Contact Me
    </h2>
    <form action="#" method="post">
     <label for="name">
      Name:
     </label>
     <br/>
     <input id="name" name="name" required="" type="text"/>
     <br/>
     <br/>
     <label for="email">
      Email:
     </label>
     <br/>
     <input id="email" name="email" required="" type="email"/>
     <br/>
     <br/>
     <label for="message">
      Message:
     </label>
     <br/>
     <textarea id="message" name="message" required="" rows="5"></textarea>
     <br/>
     <br/>
     <button type="submit">
      Send Message
     </button>
    </form>
   </div>
   <!-- ===== FOOTER ===== -->
   <div class="footer">
    <p>
     Designed by Alex Morgan | © 2026
    </p>
   </div>
  </div>
  <!-- End .container -->
 </body>
</html>

# Extract nav items

In [5]:
nav_items = soup.select("nav .nav-links li a")
nav_items

[<a href="#about">About</a>,
 <a href="#education">Education</a>,
 <a href="#projects">Projects</a>,
 <a href="#skills">Skills</a>,
 <a href="#contact">Contact</a>]

In [6]:
for i in nav_items:
    dict_items = {"Section":i.text.strip(), "Link":i.get("href")}
    print(dict_items)

{'Section': 'About', 'Link': '#about'}
{'Section': 'Education', 'Link': '#education'}
{'Section': 'Projects', 'Link': '#projects'}
{'Section': 'Skills', 'Link': '#skills'}
{'Section': 'Contact', 'Link': '#contact'}

In [7]:
nav_items = soup.select("nav .nav-links li a")
nav_data = [{"Section":link.text.strip(), "Link":link.get("href")} for link in nav_items]
nav_data

[{'Section': 'About', 'Link': '#about'},
 {'Section': 'Education', 'Link': '#education'},
 {'Section': 'Projects', 'Link': '#projects'},
 {'Section': 'Skills', 'Link': '#skills'},
 {'Section': 'Contact', 'Link': '#contact'}]

In [8]:
nav_df = pd.DataFrame(nav_data)
nav_df

     Section        Link
0      About      #about
1  Education  #education
2   Projects   #projects
3     Skills     #skills
4    Contact    #contact

### The fun begins here!

Profile

In [9]:
name = soup.select_one(".left-head h1").get_text(strip=True)

subtitle = soup.select_one(".subtitle").get_text(strip=True)

print(name)
print(subtitle)

Alex Morgan
Data Scientist | Machine Learning Enthusiast | Statistics Graduate

Contact

In [10]:
contact = soup.select_one(".contact")

contact_text = contact.get_text("\n", strip=True)

print(contact_text)

Email:
alex.morgan@example.com
LinkedIn:
linkedin.com/in/alex-morgan
GitHub:
github.com/alex-morgan
Location: Barcelona, Spain

In [11]:
contact_items = []

for p in contact.find_all("p"):
    contact_items.append(p.get_text(" ", strip=True))

contact_items

['Email: alex.morgan@example.com',
 'LinkedIn: linkedin.com/in/alex-morgan',
 'GitHub: github.com/alex-morgan',
 'Location: Barcelona, Spain']

About

In [12]:
about_section = soup.find("div", id="about")

about_text = about_section.find("p").get_text(" ", strip=True)

print(about_text)

My goal is to build cool data science projects and share them with the world!

Education

In [13]:
education_section = soup.find("div", id="education")

education = []

for item in education_section.find_all("li"):
    education.append(item.get_text(" ", strip=True))

education

['BSc (First Class Hons) in Data Science – Monash University | GPA: 3.90 / 4.00',
 'High School – Knox School | Distinction',
 'Middle School – Glen Waverly High School| Distinction']

Projects

In [14]:
projects_section = soup.find("div", id="projects")

projects = []

for item in projects_section.find_all("li"):
    projects.append(item.get_text(" ", strip=True))

projects

['DataPulse : Customer Churn Prediction with Machine Learning – Winner at DataTech 2024',
 'UrbanFlow : Travel Time Prediction with ML',
 'CreditWise : Credit Risk Classification Model',
 'StudyPath : Student Admission Predictor (R Shiny App)']

In [15]:
def split_list(input_list, splitter=":"):
    first_half = []
    last_half = []

    for input_item in input_list:
        first_half_1, last_half_1 = input_item.split(splitter, 1)

        first_half.append(first_half_1.strip())
        last_half.append(last_half_1.strip())

    return first_half, last_half
split_list(projects)

(['DataPulse', 'UrbanFlow', 'CreditWise', 'StudyPath'],
 ['Customer Churn Prediction with Machine Learning – Winner at DataTech 2024',
  'Travel Time Prediction with ML',
  'Credit Risk Classification Model',
  'Student Admission Predictor (R Shiny App)'])

Skills

In [16]:
skills_section = soup.find("div", id="skills")

skills = []

for item in skills_section.find_all("div", class_="info-box"):
    skills.append(item.get_text(" ", strip=True))

skills

['Programming: Python, R, SQL, HTML/CSS, Git',
 'Tools: Power BI, Tableau, Jupyter, TensorFlow, PostgreSQL',
 'Other: Data Visualisation, Statistical Analysis, Model Validation']

Set up a df

In [17]:
cv_data = []

# Profile
cv_data.append({
    "section": "Profile",
    "subsection": "Name",
    "content": name
})

cv_data.append({
    "section": "Profile",
    "subsection": "Title",
    "content": subtitle
})

# About
cv_data.append({
    "section": "Profile",
    "subsection": "About",
    "content": about_text
})

# Contact
for item in contact_items:
    cv_data.append({
        "section": "Contact",
        "subsection": "",
        "content": item
    })

# Education
for item in education:
    cv_data.append({
        "section": "Education",
        "subsection": "",
        "content": item
    })

# Projects
for item in projects:
    cv_data.append({
        "section": "Projects",
        "subsection": "",
        "content": item
    })

# Skills
for item in skills:
    cv_data.append({
        "section": "Skills",
        "subsection": "",
        "content": item
    })

In [18]:
cv_df = pd.DataFrame(cv_data)

cv_df

      section subsection                                            content
0     Profile       Name                                        Alex Morgan
1     Profile      Title  Data Scientist | Machine Learning Enthusiast |...
2     Profile      About  My goal is to build cool data science projects...
3     Contact                                Email: alex.morgan@example.com
4     Contact                         LinkedIn: linkedin.com/in/alex-morgan
5     Contact                                GitHub: github.com/alex-morgan
6     Contact                                    Location: Barcelona, Spain
7   Education             BSc (First Class Hons) in Data Science – Monas...
8   Education                       High School – Knox School | Distinction
9   Education             Middle School – Glen Waverly High School| Dist...
10   Projects             DataPulse : Customer Churn Prediction with Mac...
11   Projects                    UrbanFlow : Travel Time Prediction with ML
12   Projects                 CreditWise : Credit Risk Classification Model
13   Projects             StudyPath : Student Admission Predictor (R Shi...
14     Skills                    Programming: Python, R, SQL, HTML/CSS, Git
15     Skills             Tools: Power BI, Tableau, Jupyter, TensorFlow,...
16     Skills             Other: Data Visualisation, Statistical Analysi...

### Fun little side quest!

Let's make it neater

In [19]:
# Function to split the text further
def split_list(items, separator):
    result = []

    for item in items:
        first, second = item.split(separator, 1)
        result.append([first.strip(), second.strip()])

    return result

In [20]:
split_list(projects, ":")

[['DataPulse',
  'Customer Churn Prediction with Machine Learning – Winner at DataTech 2024'],
 ['UrbanFlow', 'Travel Time Prediction with ML'],
 ['CreditWise', 'Credit Risk Classification Model'],
 ['StudyPath', 'Student Admission Predictor (R Shiny App)']]

In [21]:
split_list(education, "–")

[['BSc (First Class Hons) in Data Science',
  'Monash University | GPA: 3.90 / 4.00'],
 ['High School', 'Knox School | Distinction'],
 ['Middle School', 'Glen Waverly High School| Distinction']]

In [22]:
split_list(contact_items,":")

[['Email', 'alex.morgan@example.com'],
 ['LinkedIn', 'linkedin.com/in/alex-morgan'],
 ['GitHub', 'github.com/alex-morgan'],
 ['Location', 'Barcelona, Spain']]

In [23]:
for item in split_list(contact_items,":"):
    print(item[0])

Email
LinkedIn
GitHub
Location

In [24]:
cv_data = []

# Profile
cv_data.append({
    "section": "Profile",
    "subsection": "Name",
    "content": name
})

cv_data.append({
    "section": "Profile",
    "subsection": "Title",
    "content": subtitle
})

# About
cv_data.append({
    "section": "Profile",
    "subsection": "About",
    "content": about_text
})

# Contact
for item in split_list(contact_items,":"):
    cv_data.append({
        "section": "Contact",
        "subsection": item[0],
        "content": item[1]
    })

# Education
for item in split_list(education,"–"):
    cv_data.append({
        "section": "Education",
        "subsection": item[0],
        "content": item[1]
    })

# Projects
for item in split_list(projects, ":"):
    cv_data.append({
        "section": "Projects",
        "subsection": item[0],
        "content": item[1]
    })

# Skills
for item in split_list(skills, ":"):
    cv_data.append({
        "section": "Skills",
        "subsection": item[0],
        "content": item[1]
    })

In [25]:
cv_df = pd.DataFrame(cv_data)

cv_df

,section,subsection,content
0,Profile,Name,Alex Morgan
1,Profile,Title,Data Scientist | Machine Learning Enthusiast |...
2,Profile,About,My goal is to build cool data science projects...
3,Contact,Email,alex.morgan@example.com
4,Contact,LinkedIn,linkedin.com/in/alex-morgan
5,Contact,GitHub,github.com/alex-morgan
6,Contact,Location,"Barcelona, Spain"
7,Education,BSc (First Class Hons) in Data Science,Monash University | GPA: 3.90 / 4.00
8,Education,High School,Knox School | Distinction
9,Education,Middle School,Glen Waverly High School| Distinction
10,Projects,DataPulse,Customer Churn Prediction with Machine Learnin...
11,Projects,UrbanFlow,Travel Time Prediction with ML
12,Projects,CreditWise,Credit Risk Classification Model
13,Projects,StudyPath,Student Admission Predictor (R Shiny App)
14,Skills,Programming,"Python, R, SQL, HTML/CSS, Git"
15,Skills,Tools,"Power BI, Tableau, Jupyter, TensorFlow, Postgr..."
16,Skills,Other,"Data Visualisation, Statistical Analysis, Mode..."

In [26]:
cv_df.to_excel("CV_extracted.xlsx", index=False)