API Key (Do not expose anywhere)

In [1]:
api_key = "ee892c80e8ab71002893c802c1cadaaf"

Using the request module

In [ ]:
import requests

url = "https://api.openweathermap.org/data/2.5/weather"
params1 = {"q":"Nuwara Eliya","appid":api_key,"units":"metric"}

response = requests.get(url, params = params1)
data = response.json()
data

{'coord': {'lon': 80.7829, 'lat': 6.9708},
 'weather': [{'id': 500,
   'main': 'Rain',
   'description': 'light rain',
   'icon': '10d'}],
 'base': 'stations',
 'main': {'temp': 16.19,
  'feels_like': 15.98,
  'temp_min': 16.19,
  'temp_max': 16.19,
  'pressure': 1010,
  'humidity': 81,
  'sea_level': 1010,
  'grnd_level': 854},
 'visibility': 8714,
 'wind': {'speed': 3.39, 'deg': 296, 'gust': 4.71},
 'rain': {'1h': 0.15},
 'clouds': {'all': 100},
 'dt': 1785664432,
 'sys': {'country': 'LK', 'sunrise': 1785630634, 'sunset': 1785675338},
 'timezone': 19800,
 'id': 1232783,
 'name': 'Nuwara Eliya',
 'cod': 200}

In [3]:
import pandas as pd

pd.DataFrame([data])

,coord,weather,base,main,visibility,wind,rain,clouds,dt,sys,timezone,id,name,cod
0,"{'lon': 80.7829, 'lat': 6.9708}","[{'id': 500, 'main': 'Rain', 'description': 'l...",stations,"{'temp': 16.19, 'feels_like': 15.98, 'temp_min...",8714,"{'speed': 3.39, 'deg': 296, 'gust': 4.71}",{'1h': 0.15},{'all': 100},1785664432,"{'country': 'LK', 'sunrise': 1785630634, 'suns...",19800,1232783,Nuwara Eliya,200

In [8]:
data

{'coord': {'lon': 80.7829, 'lat': 6.9708},
 'weather': [{'id': 500,
   'main': 'Rain',
   'description': 'light rain',
   'icon': '10d'}],
 'base': 'stations',
 'main': {'temp': 16.19,
  'feels_like': 15.98,
  'temp_min': 16.19,
  'temp_max': 16.19,
  'pressure': 1010,
  'humidity': 81,
  'sea_level': 1010,
  'grnd_level': 854},
 'visibility': 8714,
 'wind': {'speed': 3.39, 'deg': 296, 'gust': 4.71},
 'rain': {'1h': 0.15},
 'clouds': {'all': 100},
 'dt': 1785664432,
 'sys': {'country': 'LK', 'sunrise': 1785630634, 'sunset': 1785675338},
 'timezone': 19800,
 'id': 1232783,
 'name': 'Nuwara Eliya',
 'cod': 200}

In [4]:
city = data['name']
country = data['sys']['country']
description = data['weather'][0]['description']
temperature = data['main']['temp']
feels_like = data['main']['feels_like']
humidity = data['main']['humidity']
pressure = data['main']['pressure']
wind_speed = data['wind']['speed']
cloud_cover = data['clouds']['all']

In [5]:
weather_data = {"City":city,
"Country": country,
"Description": description,
"Temperature": temperature,
"Feels like": feels_like,
"Humidity": humidity,
"Pressure": pressure,
"Wind speed": wind_speed,
"Cloud cover": cloud_cover}

In [6]:
import pandas as pd

pd.DataFrame([weather_data])

,City,Country,Description,Temperature,Feels like,Humidity,Pressure,Wind speed,Cloud cover
0,Nuwara Eliya,LK,light rain,16.19,15.98,81,1010,3.39,100

Creating an end to end data extractor

In [30]:
cities = ["Colombo", "Jaffna"]

weather_data = []
for city in cities:
    url = "https://api.openweathermap.org/data/2.5/weather"
    params1 = {"q":city,"appid":api_key,"units":"metric"}

    response = requests.get(url, params = params1)

    data = response.json()

    city = data['name']
    country = data['sys']['country']
    description = data['weather'][0]['description']
    temperature = data['main']['temp']
    feels_like = data['main']['feels_like']
    humidity = data['main']['humidity']
    pressure = data['main']['pressure']
    wind_speed = data['wind']['speed']
    cloud_cover = data['clouds']['all']


    weather_data.append({"City":city,
    "Country": country,
    "Description": description,
    "Temperature": temperature,
    "Feels like": feels_like,
    "Humidity": humidity,
    "Pressure": pressure,
    "Wind speed": wind_speed,
    "Cloud cover": cloud_cover})

df = pd.DataFrame(weather_data)
df

,City,Country,Description,Temperature,Feels like,Humidity,Pressure,Wind speed,Cloud cover
0,Colombo,LK,light rain,30.02,35.33,71,1008,7.57,100
1,Jaffna,LK,overcast clouds,29.06,32.49,68,1006,3.22,98

In [31]:
import time
import pandas as pd
import requests

cities = ["Colombo", "Kandy", "Nuwara Eliya","Anuradhapura", "Gampaha", "Jaffna"]

weather_data = []
for city in cities:
    url = "https://api.openweathermap.org/data/2.5/weather"
    params1 = {"q":city,"appid":api_key,"units":"metric"}

    response = requests.get(url, params = params1)
    
    if response.status_code==200:
        data = response.json()

        city = data['name']
        country = data['sys']['country']
        description = data['weather'][0]['description']
        temperature = data['main']['temp']
        feels_like = data['main']['feels_like']
        humidity = data['main']['humidity']
        pressure = data['main']['pressure']
        wind_speed = data['wind']['speed']
        cloud_cover = data['clouds']['all']

        weather_data.append({"City":city,
        "Country": country,
        "Description": description,
        "Temperature (C)": temperature,
        "Feels like(C)": feels_like,
        "Humidity(%)": humidity,
        "Pressure(hPa)": pressure,
        "Wind speed(m/s)": wind_speed,
        "Cloud cover(%)": cloud_cover})

    else:
        print(f"ERROR!: Could not get data for {city} - Status code {response.status_code}")

    # Just to take time between requests so that server doesn't get overloaded
    print(f"Sleeping for 1s after {city}")
    time.sleep(1)
    # print("Back up!")

df = pd.DataFrame(weather_data)
df

Sleeping for 1s after Colombo
Sleeping for 1s after Kandy
Sleeping for 1s after Nuwara Eliya
Sleeping for 1s after Anuradhapura
Sleeping for 1s after Gampaha
Sleeping for 1s after Jaffna

,City,Country,Description,Temperature (C),Feels like(C),Humidity(%),Pressure(hPa),Wind speed(m/s),Cloud cover(%)
0,Colombo,LK,light rain,29.46,34.41,73,1008,7.57,100
1,Kandy,LK,overcast clouds,26.52,26.52,67,1009,3.24,100
2,Nuwara Eliya,LK,light rain,16.20,15.99,81,1010,3.39,100
3,Anuradhapura,LK,overcast clouds,32.05,33.76,47,1006,5.60,100
4,Gampaha,LK,overcast clouds,30.01,34.82,69,1008,5.04,100
5,Jaffna,LK,overcast clouds,29.06,32.49,68,1006,3.22,98

In [ ]:
# Rows and columns
df.shape

(6, 9)

In [32]:
df[["City", "Temperature (C)"]].sort_values(by="Temperature (C)")

           City  Temperature (C)
2  Nuwara Eliya            16.20
1         Kandy            26.52
5        Jaffna            29.06
0       Colombo            29.46
4       Gampaha            30.01
3  Anuradhapura            32.05