API Key (Do not expose anywhere)

In [7]:
api_key = "ee892c80e8ab71002893c802c1cadaaf"

Using the request module

In [8]:
import requests

url = "https://api.openweathermap.org/data/2.5/weather"
params1 = {"q":"Nuwara Eliya","appid":api_key,"units":"metric"}

response = requests.get(url, params = params1)
data = response.json()
data

{'coord': {'lon': 80.7829, 'lat': 6.9708},
 'weather': [{'id': 804,
   'main': 'Clouds',
   'description': 'overcast clouds',
   'icon': '04d'}],
 'base': 'stations',
 'main': {'temp': 13.01,
  'feels_like': 12.85,
  'temp_min': 13.01,
  'temp_max': 13.01,
  'pressure': 1012,
  'humidity': 95,
  'sea_level': 1012,
  'grnd_level': 854},
 'visibility': 1123,
 'wind': {'speed': 2.82, 'deg': 270, 'gust': 5.4},
 'clouds': {'all': 100},
 'dt': 1785583892,
 'sys': {'country': 'LK', 'sunrise': 1785544228, 'sunset': 1785588950},
 'timezone': 19800,
 'id': 1232783,
 'name': 'Nuwara Eliya',
 'cod': 200}

In [9]:
import pandas as pd

pd.DataFrame([data])

,coord,weather,base,main,visibility,wind,clouds,dt,sys,timezone,id,name,cod
0,"{'lon': 80.7829, 'lat': 6.9708}","[{'id': 804, 'main': 'Clouds', 'description': ...",stations,"{'temp': 13.01, 'feels_like': 12.85, 'temp_min...",1123,"{'speed': 2.82, 'deg': 270, 'gust': 5.4}",{'all': 100},1785583892,"{'country': 'LK', 'sunrise': 1785544228, 'suns...",19800,1232783,Nuwara Eliya,200

In [10]:
city = data['name']
country = data['sys']['country']
description = data['weather'][0]['description']
temperature = data['main']['temp']
feels_like = data['main']['feels_like']
humidity = data['main']['humidity']
pressure = data['main']['pressure']
wind_speed = data['wind']['speed']
cloud_cover = data['clouds']['all']

In [11]:
weather_data = {"City":city,
"Country": country,
"Description": description,
"Temperature": temperature,
"Feels like": feels_like,
"Humidity": humidity,
"Pressure": pressure,
"Wind speed": wind_speed,
"Cloud cover": cloud_cover}

In [12]:
import pandas as pd

pd.DataFrame([weather_data])

,City,Country,Description,Temperature,Feels like,Humidity,Pressure,Wind speed,Cloud cover
0,Nuwara Eliya,LK,overcast clouds,13.01,12.85,95,1012,2.82,100

Creating an end to end data extractor

In [13]:
import time
import pandas as pd
import requests

cities = ["Colombo", "Kandy", "Nuwara Eliya","Anuradhapura", "Gampaha", "Jaffna"]

weather_data = []
for city in cities:
    url = "https://api.openweathermap.org/data/2.5/weather"
    params1 = {"q":city,"appid":api_key,"units":"metric"}

    response = requests.get(url, params = params1)
    
    if response.status_code==200:
        data = response.json()

        city = data['name']
        country = data['sys']['country']
        description = data['weather'][0]['description']
        temperature = data['main']['temp']
        feels_like = data['main']['feels_like']
        humidity = data['main']['humidity']
        pressure = data['main']['pressure']
        wind_speed = data['wind']['speed']
        cloud_cover = data['clouds']['all']

        weather_data.append({"City":city,
        "Country": country,
        "Description": description,
        "Temperature (C)": temperature,
        "Feels like(C)": feels_like,
        "Humidity(%)": humidity,
        "Pressure(hPa)": pressure,
        "Wind speed(m/s)": wind_speed,
        "Cloud cover(%)": cloud_cover})

    else:
        print(f"ERROR!: Could not get data for {city} - Status code {response.status_code}")

    # Just to take time between requests so that server doesn't get overloaded
    print(f"Sleeping for 1s after {city}")
    time.sleep(1)
    # print("Back up!")

df = pd.DataFrame(weather_data)
df

Sleeping for 1s after Colombo
Sleeping for 1s after Kandy
Sleeping for 1s after Nuwara Eliya
Sleeping for 1s after Anuradhapura
Sleeping for 1s after Gampaha
Sleeping for 1s after Jaffna

,City,Country,Description,Temperature (C),Feels like(C),Humidity(%),Pressure(hPa),Wind speed(m/s),Cloud cover(%)
0,Colombo,LK,light rain,28.35,32.64,78,1008,7.49,100
1,Kandy,LK,overcast clouds,22.13,22.67,87,1010,2.59,100
2,Nuwara Eliya,LK,overcast clouds,13.01,12.85,95,1012,2.82,100
3,Anuradhapura,LK,overcast clouds,27.59,29.67,68,1007,6.44,100
4,Gampaha,LK,light rain,28.34,33.69,84,1009,4.08,100
5,Jaffna,LK,light rain,29.56,34.43,72,1004,7.47,100

In [17]:
# Rows and columns
df.shape

(6, 9)

In [16]:
df[["City", "Temperature (C)"]]

           City  Temperature (C)
0       Colombo            28.35
1         Kandy            22.13
2  Nuwara Eliya            13.01
3  Anuradhapura            27.59
4       Gampaha            28.34
5        Jaffna            29.56